services:
  - type: web
    name: gatekeeper-auth-api
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: PRODUCTION
      - key: PORT
        fromService:
          type: web
          name: gatekeeper-auth-api
          property: port
      # Add other environment variables manually in Render dashboard
      # or use environment groups for better management
